export const PERMISSION = {
    CREATE_PRODUCT: 0,
    READ_PRODUCT: 1,
    UPDATE_PRODUCT: 2,
    DELETE_PRODUCT: 3,

    CREATE_PRODUCT_TYPE: 4,
    READ_PRODUCT_TYPE: 5,
    UPDATE_PRODUCT_TYPE: 6,
    DELETE_PRODUCT_TYPE: 7,

    CREATE_USER: 8,
    READ_USER: 9,
    UPDATE_USER: 10,

    CREATE_ORDER: 11,
    READ_ORDER: 12,
    UPDATE_ORDER: 13,

    CREATE_DISCOUNT: 14,
    READ_DISCOUNT: 15,
    UPDATE_DISCOUNT: 16,
    DELETE_DISCOUNT: 17,

    CREATE_INVENTORY_RECEIPT: 18,
    READ_INVENTORY_RECEIPT: 19,
    UPDATE_INVENTORY_RECEIPT: 20,

    CREATE_SUPPLIER: 21,
    READ_SUPPLIER: 22,
    UPDATE_SUPPLIER: 23,

    CREATE_PERMISSION: 24,
    READ_PERMISSION: 25,
    UPDATE_PERMISSION: 26,
    DELETE_PERMISSION: 27,

    CREATE_ROLE: 28,
    READ_ROLE: 29,
    UPDATE_ROLE: 30,
    DELETE_ROLE: 31,
};
